### PR TITLE
Rather big refactoring on shell hooks; interested?

### PR DESCRIPTION
**Pull request by akatrevorjay**
Hey, I've changed the CLI a bit and updated the shell hook a bit to make it easier.
I store a new zsh hook inside of antibody using go-bindata, that I've been toying with the idea of better shell integration with.
Parts aren't fully in a done state, but if you're interested in this I'll clean it up and fix the tests.
I wanted to get your opinion though on the diff before spending the time as it's quite a change in operation.

Ty,
Trevor

### CODE REVIEW

**Comment by caarlos0** [comment]
interesting idea, if you can/will, please proceed :beers:

**Comment by caarlos0** [comment]
@akatrevorjay hey Trevor, I like the idea... if are unable to proceed, I'll pick it up. Is that OK for you?

**Comment by akatrevorjay** [comment]
Hi Carlos,

I've done a small bit to it, but feel free to continue for now if y want.
What I've began to do is try to make this usable for n number of roots,
that way I can have it manage generic bundles of repos in parallel, eg for
tmux and vim plugins as well. I'll push up what I have at least tomorrowl.
Is there a gitter around for this? Would love to chat about it and work
together on it.

On Mon, Mar 28, 2016, 12:19 AM Carlos Alexandro Becker <
notifications@github.com> wrote:

> @akatrevorjay <https://github.com/akatrevorjay> hey Trevor, I like the
> idea... if are unable to proceed, I'll pick it up. Is that OK for you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/getantibody/antibody/pull/92#issuecomment-202225123>
>
-- 
Ty,
Trevor

**Comment by akatrevorjay** [comment]
You*

On Mon, Mar 28, 2016, 12:25 AM Trevor Joynson <trevorjoynson@gmail.com>
wrote:

> Hi Carlos,
>
> I've done a small bit to it, but feel free to continue for now if y want.
> What I've began to do is try to make this usable for n number of roots,
> that way I can have it manage generic bundles of repos in parallel, eg for
> tmux and vim plugins as well. I'll push up what I have at least tomorrowl.
> Is there a gitter around for this? Would love to chat about it and work
> together on it.
>
> On Mon, Mar 28, 2016, 12:19 AM Carlos Alexandro Becker <
> notifications@github.com> wrote:
>
>> @akatrevorjay <https://github.com/akatrevorjay> hey Trevor, I like the
>> idea... if are unable to proceed, I'll pick it up. Is that OK for you?
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/getantibody/antibody/pull/92#issuecomment-202225123>
>>
> --
> Ty,
> Trevor
>
-- 
Ty,
Trevor

**Comment by caarlos0** [comment]
@akatrevorjay now it does: https://gitter.im/getantibody/antibody

**Comment by caarlos0** [comment]
done in #101

**Pull request closed without merging**
